### ISSUE TITLE
laravel 4.1.* support

### ISSUE THREAD

**Issue by lokielse** [xdubois/taxonomy-laravel-bundle#1]
What a greate and useful bundle.

laravel 4.1 throw a Excepion Controller is not found.

```
class VocabulariesController extends \Illuminate\Routing\Controllers\Controller {..}
```

change to follow will be ok.

```
class VocabulariesController extends \Illuminate\Routing\Controller {..}
```

and could you please provide more Term extend details or example?

**Comment by xdubois** [comment]
Hey lokie!se,

I am sorry I didn't see your Issue, you can find the new version of the package here 

https://github.com/DevFactoryCH/taxonomy

It includes a cleaner version of the package and a better documentation.

**Comment by lokielse** [comment]
thanks!
